name: Signs
main: fex.signs.signs.Main
version: 1.1.1
author: fex594
database: true
api-version: 1.13
commands:
   signs:
      description: Universalbefehl des Schilderplugins
      usage: </signs>
      aliases: [asi, s, sign]